apiVersion: apps/v1
kind: StatefulSet
metadata:
  # The cluster name.
  name: gridgain-cluster
  # Place your namespace name.
  namespace: gridgain
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9404"
    prometheus.io/path: "/metrics"
spec:
  # The initial number of pods to be started by Kubernetes.
  replicas: 2
  # Kubernetes service to access the GridGain 9 cluster on the Kubernetes network.
  serviceName: gridgain-svc-headless
  selector:
    matchLabels:
      app: gridgain
  template:
    metadata:
      labels:
        app: gridgain
    spec:
      terminationGracePeriodSeconds: 60000
      initContainers:
      - name: jmx-agent-download
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            wget -q -O /agent/jmx.jar \
              https://github.com/prometheus/jmx_exporter/releases/download/1.3.0/jmx_prometheus_javaagent-1.3.0.jar
        volumeMounts:
        - name: jmx-agent
          mountPath: /agent
      containers:
        # Custom pod name.
      - name: gridgain-node
        # Limits and requests for the GridGain container.
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 4Gi
        env:
          # Must be specified to ensure that GridGain 9 cluster replicas are visible to each other.
          - name: GRIDGAIN_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # GridGain 9 working directory.
          - name: GRIDGAIN_WORK_DIR
            value: /gg9-work
          # Test for JMX
          - name: GRIDGAIN9_EXTRA_JVM_ARGS
            value: "-javaagent:/agent/jmx.jar=9404:/opt/jmx/jmx.yaml"
        # GridGains Docker image and it's version.
        image: gridgain/gridgain9:9.1.1
        # image: docker.gridgain.com/docker-dev/gridgain/gridgain9@sha256:6ecee996640806a45ce4bee338061c9f2f2f3be3e562923a2498cba1cd1b184e
        ports:
        - containerPort: 10300
        - containerPort: 10800
        - containerPort: 3344
        - containerPort: 9404
        volumeMounts:
        # The config will be placed at this path in the container.
        - mountPath: /opt/gridgain/etc/gridgain-config.conf
          name: config-vol
          subPath: gridgain-config.conf
        # The license will be placed at this path in the container.
        - mountPath: /opt/gridgain/etc/gridgain-license.conf
          name: license-vol
          subPath: gridgain-license.conf
        # GridGain 9 working directory.
        - mountPath: /gg9-work
          name: persistence
        # jmx agent
        - name: jmx-agent
          mountPath: /agent
        - name: jmx-config
          mountPath: /opt/jmx/jmx.yaml
          subPath: jmx.yaml
      # For private docker repo i.e. unrealsed GG version
      # imagePullSecrets:
      #   - name: harbor-secrets
      volumes:
      - name: config-vol
        configMap:
          name: gridgain-config
      - name: license-vol
        configMap:
          name: gridgain-license
      - name: jmx-agent
        emptyDir: {}
      - name: jmx-config
        configMap:
          name: jmx-config
      # securityContext:
      #   runAsUser: 0
      #   runAsGroup: 0
      #   fsGroup: 0
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: persistence
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi # Provide enough space for your application data.
      volumeMode: Filesystem