alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "gridgain"
        metrics_path: "/metrics"
        dns_sd_configs:
          - names:
              - "gridgain-svc-headless.gridgain.svc.cluster.local"
            type: A
            port: 9404
            refresh_interval: 30s