license:
# -- path inside GridGain container to mount the file with license
  mountPath: /opt/gridgain/etc/license.conf
# -- Create secret from raw content passed
  createSecret: 
    mountPath: /opt/gridgain/etc
# -- License raw content
    content: |
      ignite {
        license {
          content:"<Put your license here>"
        }
      }
