#
# Copyright (C) GridGain Systems. All Rights Reserved.
#  _________        _____ __________________        _____
#  __  ____/___________(_)______  /__  ____/______ ____(_)_______
#  _  / __  __  ___/__  / _  __  / _  / __  _  __ `/__  / __  __ \
#  / /_/ /  _  /    _  /  / /_/ /  / /_/ /  / /_/ / _  /  _  / / /
#  \____/   /_/     /_/   \_,__/   \____/   \__,_/  /_/   /_/ /_/
#

{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name | default (include "gridgain9.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  egress: {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  ingress: {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  podSelector:
    matchLabels: {{- include "gridgain9.selectorLabels" $ | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
