{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gridgain9.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "gridgain9.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.serviceMonitor.namespaceSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.selector }}
  selector:
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
  {{- else }}
  selector:
    matchLabels:
      {{- include "gridgain9.selectorLabels" . | nindent 6 }}
  {{- end }}
  endpoints:
    {{- if .Values.serviceMonitor.endpoints }}
    {{- toYaml .Values.serviceMonitor.endpoints | nindent 4 }}
    {{- else }}
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.serviceMonitor.targetLabels }}
      targetLabels:
        {{- toYaml .Values.serviceMonitor.targetLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.podTargetLabels }}
      podTargetLabels:
        {{- toYaml .Values.serviceMonitor.podTargetLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.sampleLimit }}
      sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}
      {{- end }}
      {{- if .Values.serviceMonitor.targetLimit }}
      targetLimit: {{ .Values.serviceMonitor.targetLimit }}
      {{- end }}
      {{- if .Values.serviceMonitor.labelLimit }}
      labelLimit: {{ .Values.serviceMonitor.labelLimit }}
      {{- end }}
      {{- if .Values.serviceMonitor.labelNameLengthLimit }}
      labelNameLengthLimit: {{ .Values.serviceMonitor.labelNameLengthLimit }}
      {{- end }}
      {{- if .Values.serviceMonitor.labelValueLengthLimit }}
      labelValueLengthLimit: {{ .Values.serviceMonitor.labelValueLengthLimit }}
      {{- end }}
    {{- end }}
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
{{- end }} 