{{- if and ( eq .Values.spring.config.type "file") (hasKey .Values.spring.config "content") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cc-spring-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cc-spring-app.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.spring.config.name }}: |
{{ .Values.spring.config.content | indent 4  }}
{{- end }}

