{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cc-spring-app.fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cc-spring-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cc-spring-app.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $httpPort }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end -}}