{{- if .Values.serviceAccount.create -}}
{{- $serviceAccountName := include "cc-spring-app.serviceAccountName" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName  }}-role-bind-auth-delegate
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cc-spring-app.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}