#
# Copyright (C) GridGain Systems. All Rights Reserved.
#  _________        _____ __________________        _____
#  __  ____/___________(_)______  /__  ____/______ ____(_)_______
#  _  / __  __  ___/__  / _  __  / _  / __  _  __ `/__  / __  __ \
#  / /_/ /  _  /    _  /  / /_/ /  / /_/ /  / /_/ / _  /  _  / / /
#  \____/   /_/     /_/   \_,__/   \____/   \__,_/  /_/   /_/ /_/
#

{{- if .Values.license.fromFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "gridgain.fullname" .) "license" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "gridgain.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  gridgain-license.xml: |-
{{ tpl ( .Files.Get ( printf "%s" .Values.license.fromFile.filepath ) ) . | b64enc | indent 4 }}
---
{{- end }}
